CREATE VIEW CONTACT
    AS SELECT NAME, PHONE FROM PUBLISHER;

CREATE OR REPLACE VIEW CONTACT
    AS SELECT NAME, PHONE FROM PUBLISHER
    WITH READ ONLY;

CREATE FORCE VIEW HOMEWORK13
    AS SELECT COL1, COL2 FROM FIRSTATTEMPT;
    
DESC HOMEWORK13;    

CREATE VIEW REORDERINFO
    AS SELECT ISBN, B.TITLE, CONTACT, PHONE FROM BOOKS B JOIN PUBLISHER USING(PUBID);

UPDATE REORDERINFO SET CONTACT = 'THANH NGUYEN' WHERE PHONE = '000-714-8321';

UPDATE REORDERINFO SET ISBN = 00001110 WHERE TITLE = 'REVENGE OF MICKEY';

DELETE FROM REORDERINFO WHERE CONTACT = 'TOMMIE SEYMOUR';

ROLLBACK;

DROP VIEW REORDERINFO;

THANH NGUYEN