SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE PROMO_SHIP_SP
    (SPEC_DATE IN DATE)
IS
    IDS BB_BASKET.IDSHOPPER%TYPE;
    MAX_D BB_BASKET.DTCREATED%TYPE;
BEGIN
    SELECT IDSHOPPER, MAX(DTCREATED) INTO IDS, MAX_D FROM BB_BASKET GROUP BY IDSHOPPER HAVING MAX(DTCREATED) < '01-APR-12';
    INSERT INTO BB_PROMOLIST (idshopper, month, year, promo_flag, used)VALUES (IDS, 'APR', '2012', '1', 'N');
END;

DECLARE
    DT DATE := '01-APR-12';
BEGIN
    PROMO_SHIP_SP(DT);
END;

THANH NGUYEN

SELECT*FROM BB_PROMOLIST;

CREATE OR REPLACE PROCEDURE DDCKPAY_SP (PAY IN NUMBER, IDP IN NUMBER, CONFIRM_P OUT VARCHAR2) 
IS 
    pledge_id DD_PLEDGE.idpledge%TYPE; 
    pledge_amt DD_PLEDGE.pledgeamt%TYPE; 
    pay_months DD_PLEDGE.paymonths%TYPE; 
    AMT_LEFT DD_PLEDGE.paymonths%TYPE; 
BEGIN SELECT PAYMONTHS, IDPLEDGE, PLEDGEAMT INTO PAY_MONTHS, PLEDGE_ID, PLEDGE_AMT FROM DD_PLEDGE WHERE IDPLEDGE = IDP; 
    IF PAY_MONTHS > 0 THEN AMT_LEFT := PLEDGE_AMT/PAY_MONTHS; 
    END IF;
         IF AMT_LEFT =20 THEN 
            CONFIRM_P := 'The payment is the correct monthly increment amount';
            DBMS_OUTPUT.PUT_LINE(CONFIRM_P); 
         ELSE RAISE_APPLICATION_ERROR(-20050,'Incorrect payment amount - planned payment = '||AMT_LEFT); 
         
    END IF; 
END;

DECLARE 
    DETAIL VARCHAR2(60);
BEGIN
    DDCKPAY_SP(25, 104, DETAIL); 
END;


THANH NGUYEN