CREATE OR REPLACE TRIGGER bb_reorder_trg
   AFTER UPDATE OF stock ON bb_product
   FOR EACH ROW 
DECLARE
  v_onorder_num NUMBER(4);
 BEGIN
  If :NEW.stock <= :NEW.reorder THEN
   SELECT SUM(qty)
    INTO v_onorder_num
    FROM bb_product_request
    WHERE idProduct = :NEW.idProduct
     AND dtRecd IS NULL;
   IF v_onorder_num IS NULL THEN v_onorder_num := 0; END IF;
   IF v_onorder_num = 0 THEN
     INSERT INTO bb_product_request (idRequest, idProduct, dtRequest, qty)
       VALUES (bb_prodreq_seq.NEXTVAL, :NEW.idProduct, SYSDATE, :NEW.reorder);
   END IF;
  END IF;
END;

THANH NGUYEN

SELECT STOCK, REORDER FROM BB_PRODUCT WHERE IDPRODUCT = 4;

UPDATE BB_PRODUCT SET STOCK = 25 WHERE IDPRODUCT = 4;

SELECT*FROM BB_PRODUCT_REQUEST;

ROLLBACK;

INSERT INTO bb_product_request (idRequest, idProduct, dtRequest, qty) VALUES (3, 5, SYSDATE, 45);

COMMIT;

CREATE OR REPLACE TRIGGER BB_REQFILL_TRG
   AFTER UPDATE OF DTRECD ON bb_product_REQUEST
   FOR EACH ROW 
 BEGIN
  UPDATE BB_PRODUCT SET STOCK = STOCK + :NEW.QTY WHERE IDPRODUCT = :NEW.IDPRODUCT;
END;

SELECT STOCK, REORDER FROM BB_PRODUCT WHERE IDPRODUCT = 5;

THANH NGUYEN

SELECT*FROM BB_PRODUCT_REQUEST WHERE IDPRODUCT = 5;

UPDATE BB_PRODUCT_REQUEST SET DTRECD = SYSDATE, COST = 225 WHERE IDREQUEST =3;

SELECT*FROM BB_PRODUCT_REQUEST WHERE IDPRODUCT = 5;

SELECT STOCK, REORDER FROM BB_PRODUCT WHERE IDPRODUCT = 5;

ROLLBACK;

CREATE OR REPLACE TRIGGER BB_REQFILL_TRG
   AFTER UPDATE OF DTRECD ON bb_product_REQUEST
   FOR EACH ROW 
 BEGIN
  IF :NEW.DTRECD = NULL THEN
    UPDATE BB_PRODUCT SET STOCK = STOCK + :NEW.QTY WHERE IDPRODUCT = :NEW.IDPRODUCT;
  END IF;  
END;

INSERT INTO bb_product_request (idRequest, idProduct, dtRequest, qty, dtRecd, cost) VALUES (4, 5, SYSDATE, 45, '15-JUN-2012',225);

UPDATE bb_product SET stock = 76 WHERE idProduct = 5;

COMMIT;
DELETE FROM BB_PRODUCT_REQUEST WHERE IDREQUEST = 4;
DELETE FROM BB_PRODUCT_REQUEST WHERE IDREQUEST = 3;


UPDATE bb_product_request
SET dtRecd = NULL
WHERE idRequest = 4;

ALTER TRIGGER bb_reqfill_trg DISABLE;
SELECT*FROM BB_PRODUCT_REQUEST;
SELECT*FROM BB_PRODUCT;


THANH NGUYEN
