CREATE TABLE STUDENT (ST_NUMBER NUMBER(6), ST_LAST VARCHAR2(35) NOT NULL, ST_FIRST VARCHAR2(25), 
ST_DOB DATE, CONSTRAINT STUDENT_ST_NUMBER_pk PRIMARY KEY (ST_NUMBER));

CREATE TABLE VENDOR (VEND_NUMBER NUMBER(5), VEND_NAME VARCHAR2(35) NOT NULL,
CONSTRAINT VENDOR_VEND_NUMBER_pk PRIMARY KEY (VEND_NUMBER));

CREATE TABLE PRODUCT (PROD_CODE NUMBER(5), PROD_DESC VARCHAR2(35),
CONSTRAINT PRODUCT_PROD_CODE_pk PRIMARY KEY (PROD_CODE));

CREATE TABLE VEND_PROD (ID NUMBER(10), VEND_NUMBER NUMBER(5), PROD_CODE NUMBER(5),
CONSTRAINT VEND_PROD_ID_pk PRIMARY KEY (ID),
CONSTRAINT VEND_PROD_VEND_NUMBER_pk FOREIGN KEY (VEND_NUMBER) REFERENCES VENDOR (VEND_NUMBER),
CONSTRAINT VEND_PROD_PROD_CODE_pk FOREIGN KEY (PROD_CODE) REFERENCES PRODUCT (PROD_CODE)
);

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PROD_DESC_uk UNIQUE (PROD_DESC);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_ST_DOB_ck CHECK (ST_DOB > '01-JAN-2000');


THANH NGUYEN