SELECT 'THANH NGUYEN' FROM DUAL;

SELECT INITCAP('THANH NGUYEN') FROM DUAL;

SELECT INSTR('THANH NGUYEN',' ') FROM DUAL; 

SELECT SUBSTR('THANH NGUYEN',7,6) FROM DUAL; 

SELECT SUBSTR('THANH NGUYEN', 1, INSTR('THANH NGUYEN',' ',-1)) FROM DUAL; 

SELECT SUBSTR('THANH NGUYEN',INSTR('THANH NGUYEN',' '), LENGTH('THANH NGUYEN')) FROM DUAL; 

SELECT CONCAT(CONCAT('THANH', ' '), 'NGUYEN') FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT TRUNC(MONTHS_BETWEEN('24-DEC-21', SYSDATE),0) FROM DUAL;

SELECT TO_DATE('JANUARY 21, 2013', 'MONTH DD, YYYY') FROM DUAL;

SELECT TO_CHAR(TO_DATE('21-JAN-13', 'DD-MON-YY'), 'MONTH DD, YYYY') FROM DUAL;

THANH NGUYEN