USE tnguy22;
SELECT CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME, ORDER_NUM FROM CUSTOMER LEFT JOIN ORDERS ON ORDERS.CUSTOMER_NUM= CUSTOMER.CUSTOMER_NUM;
SELECT CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME, ORDER_NUM FROM CUSTOMER RIGHT JOIN ORDERS ON ORDERS.CUSTOMER_NUM= CUSTOMER.CUSTOMER_NUM;

SELECT CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME, ORDER_NUM FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM;
SELECT CUSTOMER_NAME FROM CUSTOMER LEFT JOIN ORDERS ON ORDERS.CUSTOMER_NUM= CUSTOMER.CUSTOMER_NUM;
SELECT CUSTOMER_NAME FROM CUSTOMER RIGHT JOIN ORDERS ON ORDERS.CUSTOMER_NUM= CUSTOMER.CUSTOMER_NUM;

SELECT PART_NUM, DESCRIPTION FROM PART WHERE PART_NUM IN (SELECT PART_NUM FROM ORDER_LINE);
SELECT PART_NUM, DESCRIPTION FROM PART WHERE PART_NUM NOT IN (SELECT PART_NUM FROM ORDER_LINE);

SELECT LAST_NAME AS 'CUSTOMER OR REP NAME' FROM REP WHERE CITY = 'Grove' UNION SELECT CUSTOMER_NAME FROM CUSTOMER WHERE CITY = 'Grove';
SELECT REP.LAST_NAME, CUSTOMER.CUSTOMER_NAME FROM REP, CUSTOMER WHERE REP.CITY = 'Grove' AND CUSTOMER.CITY = 'Grove' UNION SELECT REP.LAST_NAME, CUSTOMER.CUSTOMER_NAME FROM REP, CUSTOMER WHERE CUSTOMER.CITY = REP.CITY;

SELECT CUSTOMER_NUM, CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_NUM IN(SELECT CUSTOMER_NUM FROM ORDERS WHERE ORDER_DATE <> '2007-10-21');
SELECT ORDER_DATE, CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME FROM CUSTOMER, ORDERS WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_DATE <> '2007-10-21';

SELECT ORDERS.CUSTOMER_NUM, CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_DATE <> '2007-10-21';


SELECT PART_NUM, DESCRIPTION, (ON_HAND*PRICE) AS 'ON HAND VALUE' FROM PART WHERE ON_HAND*PRICE BETWEEN 500 AND 10000;







SELECT PART_NUM, DESCRIPTION, (ON_HAND*PRICE) AS 'ON HAND VALUE' FROM PART WHERE ON_HAND*PRICE BETWEEN 500 AND 10000;
SELECT CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME FROM CUSTOMER, ORDERS WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUTSOMER_NUM AND ORDER_DATE <> '2007-10-21';
SELECT CUSTOMER_NUM, CUSTOMER_NAME FROM CUSTOMER, ORDERS WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUTSOMER_NUM AND ORDER_DATE <> '2007-10-21';
SELECT*FROM ORDERS;
SELECT*FROM CUSTOMER;
SELECT ORDERS.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION, CLASS FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND (CLASS ='AP' OR CLASS = 'HW');
SELECT ORDER_LINE.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION, CLASS FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND CLASS ='AP' OR CLASS = 'HW';
SELECT ORDERS.ORDER_NUM, CUSTOMER_NAME, PART.DESCRIPTION, CLASS FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND CLASS ='AP' OR CLASS = 'HW';
SELECT ORDERS.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION, CLASS FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND CLASS ='AP' OR CLASS = 'HW';
SELECT ORDERS.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM;
SELECT ORDER_LINE.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT ORDERS.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION, CLASS FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND CLASS ='AP' OR CLASS = 'HW';
SELECT ORDERS.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION, CLASS FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOEMR_NUM = ORDERS.CUSTOMER_NUM AND ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM AND CLASS ='AP' OR CLASS = 'HW';
SELECT ORDER_LINE.ORDER_NUM, CUSTOMER_NAME, DESCRIPTION FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT CUSTOMER_NAME, ORDER_LINE.ORDER_NUM, DESCRIPTION FROM CUSTOMER, ORDERS, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT CUSTOMER_NAME, ORDER_LINE.ORDER_NUM, PART.DESCRIPTION FROM CUSTOMER, ORDER_LINE, PART WHERE ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT ORDERS.ORDER_NUM, ORDER_DATE, DESCRIPTION, PRICE FROM ORDERS, ORDER_LINE, PART WHERE ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM ORDER BY PRICE DESC;
SELECT ORDERS.ORDER_NUM, ORDER_DATE, DESCRIPTION, PRICE FROM ORDERS, ORDER_LINE, PART WHERE ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT ORDERS.ORDER_NUM, ORDER_DATE, DESCRIPTION, PRICE FROM ORDERS, ORDER_LINE, PART WHERE ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM ORDER BY PRICE DESC;
SELECT ORDERS.ORDER_NUM, ORDER_DATE, DESCRIPTION, PRICE FROM ORDERS, ORDER_LINE, PART WHERE ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM ORDER BY PRICE_DESC;
SELECT ORDERS.ORDER_NUM, ORDER_DATE, DESCRIPTION, PRICE FROM ORDERS, ORDER_LINE, PART WHERE ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT*FROM PART;
SELECT ORDER_NUM, ORDER_DATE, PART.DESCRIPTION, PRICE FROM ORDERS, PART WHERE ORDERS.ORDER_NUM = PART.ORDER_NUM

SELECT CUSTOMER_NAME, ORDER_LINE.ORDER_NUM, PART.DESCRIPTION FROM CUSTOMER, ORDER_LINE, PART WHERE ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT*FROM CUSTOMER;
SELECT*FROM ORDER_LINE;
SELECT*FROM PART;
SELECT*FROM ORDER_LINE;
SELECT ORDER_NUM, ORDER_DATE, PART.DESCRIPTION, PRICE FROM ORDERS, PART WHERE ORDERS.ORDER_NUM = PART.ORDER_NUM

SELECT CUSTOMER_NAME, ORDER_LINE.ORDER_NUM, PART.DESCRIPTION FROM CUSTOMER, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.PART_NUM = PART.PART_NUM;
SELECT*FROM PART;
SELECT ORDER_NUM, ORDER_DATE, PART.DESCRIPTION, PRICE FROM ORDERS, PART WHERE ORDERS.ORDER_NUM = PART.ORDER_NUM

SELECT CUSTOMER_NAME, ORDER_LINE.ORDER_NUM, PART.DESCRIPTION FROM CUSTOMER, ORDER_LINE, PART WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.ORDER_NUM = PART.ORDER_NUM;
SELECT*FROM ORDER_LINE;


SELECT CUSTOMER.CUSTOMER_NAME, ORDER_LINE.ORDER_NUM, PART.DESCRIPTION WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM AND ORDER_LINE.ORDER_NUM = PART.ORDER_NUM;

SELECT*FROM PART;
SELECT*FROM ORDERS;

SELECT ORDER_NUM, PART.PART_NUM, DESCRIPTION, WAREHOUSE, PRICE FROM PART, ORDER_LINE WHERE ORDER_LINE.PART_NUM = PART.PART_NUM AND (WAREHOUSE = '3' OR PRICE >= 500);
SELECT ORDER_NUM, ORDER_DATE, CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME FROM ORDERS, CUSTOMER WHERE ORDERS.CUSTOMER_NUM= CUSTOMER.CUSTOMER_NUM AND ORDER_DATE = '2007-10-21' AND CITY ='Grove';


SELECT ORDER_NUM, ORDER_DATE, CUSTOMER.CUSTOMER_NAME FROM ORDERS, CUSTOMER WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM;
SELECT*FROM CUSTOMER;


INSERT INTO CUSTOMER
VALUES
('725','Deerfield''s Four Seasons','282 Columbia','Sheldon','FL','33553',248.00,7500.00,'35');
INSERT INTO CUSTOMER
VALUES
('842','All Season','28 Lakeview','Grove','FL','33321',8221.00,7500.00,'20');
THANH NGUYEN

SELECT*FROM CUSTOMER;
CREATE TABLE CUSTOMER
(CUSTOMER_NUM CHAR(3) PRIMARY KEY,
CUSTOMER_NAME CHAR(35) NOT NULL,
STREET CHAR(15),
CITY CHAR(15),
STATE CHAR(2),
ZIP CHAR(5),
BALANCE DECIMAL(8,2),
CREDIT_LIMIT DECIMAL(8,2),
REP_NUM CHAR(2),
FOREIGN KEY (REP_NUM) REFERENCES REP (REP_NUM));
THANH NGUYEN

SELECT*FROM ORDERS;
SELECT*FROM REP;
SELECT ORDER_NUM, ORDER_DATE FROM ORDERS WHERE CUSTOMER_NUM='608';
INSERT INTO CUSTOMER
VALUES
('148','Al''s Appliance and Sport','2837 Greenway','Fillmore','FL','33336',6550.00,7500.00,'20');
INSERT INTO CUSTOMER
VALUES
('282','Brookings Direct','3827 Devon','Grove','FL','33321',431.50,10000.00,'35');
INSERT INTO CUSTOMER
VALUES
('356','Ferguson''s','382 Wildwood','Northfield','FL','33146',5785.00,7500.00,'65');
INSERT INTO CUSTOMER
VALUES
('408','The Everything Shop','1828 Raven','Crystal','FL','33503',5285.25,5000.00,'35');
INSERT INTO CUSTOMER
VALUES
('462','Bargains Galore','3829 Central','Grove','FL','33321',3412.00,10000.00,'65');
INSERT INTO CUSTOMER
VALUES
('524','Kline''s','838 Ridgeland','Fillmore','FL','33336',12762.00,15000.00,'20');
INSERT INTO CUSTOMER
VALUES
('608','Johnson''s Department Store','372 Oxford','Sheldon','FL','33553',2106.00,10000.00,'65');
INSERT INTO CUSTOMER
VALUES
('687','Lee''s Sport and Appliance','282 Evergreen','Altonville','FL','32543',2851.00,5000.00,'35');
INSERT INTO CUSTOMER
VALUES
('725','Deerfield''s Four Seasons','282 Columbia','Sheldon','FL','33553',248.00,7500.00,'35');
INSERT INTO CUSTOMER
VALUES
('842','All Season','28 Lakeview','Grove','FL','33321',8221.00,7500.00,'20');
THANH NGUYEN

SELECT*FROM CUSTOMER;
